spring:
  redis:
    database: 0
    host: redis
    port: 6379
    password: mountain372830
    jedis:
      pool:
        max-active: 300
        max-idle: 10
  datasource:
    url: jdbc:mysql://mysql:3306/qing_yuan?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: guddqs
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 120
      minimum-idle: 30
server:
  port: 8080
  tomcat:
    max-threads: 500
    max-connections: 2000
    accept-count: 300
  servlet:
    context-path: /xxx